name: KBase SDK Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kb-sdk
        run: |
          mkdir -p $(pwd)/bin
          docker run ghcr.io/kbase/kb_sdk_patch-develop:br-0.0.4 genscript > $(pwd)/bin/kb-sdk
          chmod 755 $(pwd)/bin/kb-sdk
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Setup test config
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          sed -i "s/^test_token=.*$/test_token=$KBASE_TEST_TOKEN/g" ./test_local/test.cfg

      - name: Run tests
        run: kb-sdk test
