name: KBase SDK Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download kb-sdk and set up path
        run: |
          mkdir -p $(pwd)/bin
          docker run ghcr.io/kbase/kb_sdk_patch-develop:br-0.0.4 genscript > $(pwd)/bin/kb-sdk
          chmod 755 $(pwd)/bin/kb-sdk
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Setup and run KBase SDK Tests
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk test || true
          sed "s/^test_token=.*$/test_token=$KBASE_TEST_TOKEN/g" ./test/test.cfg.example > ./test_local/test.cfg
          kb-sdk test
